Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> in_room(bananas). in_room(chair).
... in_room(monkey). clever(monkey).
... can_climb(monkey, chair). tall(chair).
... can_move(monkey, chair, bananas).
... 
... 
... can_reach(X, Y):-
... clever(X),close(X, Y).
... 
... 
... get_on(X,Y):- can_climb(X,Y). under(Y,Z):-
... 
... in_room(X),in_room(Y),in_room(Z),can_climb(X,Y,Z). close(X,Z):-get_on(X,Y),
... 
... under(Y,Z);
... tall(Y).
